### ISSUE TITLE
Alguns erros

### ISSUE THREAD

**Issue by jaquelineDEoliveira** [WalissonPires/SistemaTNE#4]
muito claro a validação da pagina de login
se o usuário digitar senha errada por exemplo
vai demorar um tempo pra ver a advertência

Erro mais explicito
se foi na senha ou o nome do usuário

data de nascimento
campo poderia ser automaticamente preenchido por /

não tem nada informando que foi salvo os dados do novo cliente
e campos de validação

**Comment by WalissonPires** [comment]
> muito claro a validação da pagina de login

Qual validação?  (Mensagem, Bordar de campo obrigatório)

> se o usuário digitar senha errada por exemplo
vai demorar um tempo pra ver a advertência

OK.  Vou vê se adiciono um **load**.

> Erro mais explicito
se foi na senha ou o nome do usuário

Isso foi intencional.  Assim evita de pessoas mal intencionadas ficarem tentando descobri login de acesso. 

> data de nascimento
campo poderia ser automaticamente preenchido por /

não tem nada informando que foi salvo os dados do novo cliente
e campos de validação

Acesse a versão atual do sistema. (Esse problemas não existem)

**Comment by WalissonPires** [comment]
> se o usuário digitar senha errada por exemplo
vai demorar um tempo pra ver a advertência

Resolvido
