### ISSUE TITLE
Sugestão para login

### ISSUE THREAD

**Issue by DougSF** [WalissonPires/SistemaTNE#5]
**Tipo**
Sugestão

**Descrição**
Colocar case sensitive também no login. Atualmente, posso escrever o login de qualquer jeito

![tela1](https://cloud.githubusercontent.com/assets/17281436/15270585/67085bba-19fb-11e6-993d-cb018205645b.PNG)

Loguei sem problemas:
![tela2](https://cloud.githubusercontent.com/assets/17281436/15270595/9a4f7418-19fb-11e6-8db9-c5e380e51237.PNG)

**Comment by WalissonPires** [comment]
Foi de propósito, o padrão é casesensitive.  Pois o usuário é burro.  Então assim é melhor.
