### ISSUE TITLE
Alteração de Senha do usuário "versão atual" rsrs

### ISSUE THREAD

**Issue by jaquelineDEoliveira** [WalissonPires/SistemaTNE#6]
Ao alterar senha do usuário, 
fiquei sem saber para que serve a caixa de texto abaixo
e não tem nada informando se foi alterada ou não a senha,
não sei se alterou ou não, ao clicar em salvar nada ocorreu.

**Comment by WalissonPires** [comment]
![s1](https://cloud.githubusercontent.com/assets/16159193/15292931/ea707562-1b5b-11e6-83fb-07377527bacb.PNG)
![s2](https://cloud.githubusercontent.com/assets/16159193/15292936/edf70fa2-1b5b-11e6-967a-20aa866c322c.PNG)

Não vejo esses problemas.
